### PR TITLE
Fix refreshes after joining raid, unselect weapon

### LINKED ISSUE #1615: Raid join lacking value refresh
After joining a raid, the skill counter in the top right isn't updated.
Characters and their weapons do seem to update their stamina/durability EVENTUALLY but i suspect it's not directly from the raid join action, but rather a looping update somewhere else. The page also doesn't unselect the character and weapon you've just joined with.

### PR DESCRIPTION
**Pull request by Chriserus**
### All Submissions

* [ ] Can you post a screenshot of your changes (if applicable)?

### New Feature Submissions

* [ ] Does this relate to an existing issue, or has it been talked about prior to being done (if a major change)?

### Notes

Please note, your code must pass all tests and lint checks before it can be merged.

### PR Description

Closes #1615

Balances fetch correctly now, same for weapon durability and character stamina. Weapon gets unselected when joined. Minor performance improvements.

### Testing

Has the code been tested, or does it need double checking?

### CODE REVIEW

File: frontend/src/views/Raid.vue [hunk 1]
```diff
@@ -23,7 +23,7 @@
                     <div class="boss-name">
                       <div>
                         <div class="elements">
-                          <div class="frame-element">.</div>
+                          <div class="frame-element"/>
```
Comment (kevinunger) [inline frontend/src/views/Raid.vue:26]: https://html.spec.whatwg.org/multipage/syntax.html#elements-2

**Review by kevinunger — APPROVED** [review]

**Comment by kevinunger** [comment]
approved
